language: go

env:
  global:
    - GO111MODULE="on"

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls

script:
  - go install ./...
  - go test -v ./...
